<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Brand_myntraweb-sprite filter-search-c_45ae67</name>
   <tag></tag>
   <elementGuidId>22f1c0d6-4918-4639-a6a7-3e676c3fa335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.myntraweb-sprite.filter-search-closeSearch.sprites-remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[4]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>597746f0-22af-4150-ba5f-769667263a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>myntraweb-sprite filter-search-closeSearch sprites-remove</value>
      <webElementGuid>7082d5a5-d544-4561-8a4a-7cf9babb0af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[1]/main[@class=&quot;search-base&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;search-leftContainer column-base&quot;]/section[1]/div[@class=&quot;condition-render-verticalFilters condition-render-boundary-top&quot;]/div[@class=&quot;vertical-filters-filters brand-container&quot;]/div[@class=&quot;filter-search-filterSearchBox filter-search-expanded&quot;]/span[@class=&quot;myntraweb-sprite filter-search-closeSearch sprites-remove&quot;]</value>
      <webElementGuid>b39177f6-11dc-43d5-bd6b-5490def6c89b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[4]/div/span</value>
      <webElementGuid>e89031fc-1f38-4c3e-b0bf-cd9ba5fc22c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span</value>
      <webElementGuid>1b1f8db8-4e96-4f19-acbd-b497353d31c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
