<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEARCH</name>
   <tag></tag>
   <elementGuidId>55a8edf8-b58c-40d1-8c02-14f940584ffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SearchBoxContainer']/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.Searchbox__searchButton.Searchbox__searchButton--active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0181d68-f85d-4691-89c5-f0d425c522d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn Searchbox__searchButton Searchbox__searchButton--active</value>
      <webElementGuid>66abd3d3-9f18-4b0d-aaec-0db077a41911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selenium</name>
      <type>Main</type>
      <value>searchButton</value>
      <webElementGuid>997eecf0-7ace-41ca-847f-8793119f270e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>search-button</value>
      <webElementGuid>308325de-1851-4146-b204-6a9ef45261f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>64914f05-cdc8-41e6-8d28-eed0bed45efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBoxContainer&quot;)/div[@class=&quot;Searchbox Searchbox--horizontal&quot;]/div[@class=&quot;Searchbox__wrapper&quot;]/button[@class=&quot;btn Searchbox__searchButton Searchbox__searchButton--active&quot;]</value>
      <webElementGuid>a07e1d2c-0074-46d3-bcf1-298e934e2c0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBoxContainer']/div/div/button</value>
      <webElementGuid>6b5653db-3d6a-4009-8616-7fd7a60f160d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wednesday'])[1]/following::button[1]</value>
      <webElementGuid>6c9761bb-1418-4ae5-97b7-91c3a6220bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friday'])[1]/following::button[1]</value>
      <webElementGuid>4023e270-6526-49ec-b0c9-cbea7477e30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solo traveler'])[1]/preceding::button[1]</value>
      <webElementGuid>922ad378-350c-40ae-827b-53278b9901cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>443614b9-b771-4bb8-824c-834d57120ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>4ce82344-c460-44b2-aee6-f8713a5f69fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
