<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(112677)_common-checkboxIndicator</name>
   <tag></tag>
   <elementGuidId>ad4760db-aaec-4128-b005-1a9375566970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.common-checkboxIndicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[2]/ul/li/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d353f1fe-a1a5-409d-bc95-fb9e36c0b82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common-checkboxIndicator</value>
      <webElementGuid>b3e9ecad-e685-4583-ad0c-bfce77d27a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[1]/main[@class=&quot;search-base&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;search-leftContainer column-base&quot;]/section[1]/div[@class=&quot;condition-render-verticalFilters condition-render-boundary-top&quot;]/div[@class=&quot;vertical-filters-filters categories-container&quot;]/ul[@class=&quot;categories-list&quot;]/li[1]/label[@class=&quot;common-customCheckbox vertical-filters-label&quot;]/div[@class=&quot;common-checkboxIndicator&quot;]</value>
      <webElementGuid>24ef99e6-69d5-4fee-b776-2de20b958219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[2]/ul/li/label/div</value>
      <webElementGuid>124d41c9-6035-4afe-ba22-55cb50602c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>a77449c5-979d-4a1a-9afc-daec3de4cc5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
