<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Recommended_myntraweb-sprite sort-down_d6ab57</name>
   <tag></tag>
   <elementGuidId>86e638bd-69ee-4cdf-a0a4-e8cbed5b3b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.myntraweb-sprite.sort-downArrow.sprites-downArrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='desktopSearchResults']/div/section/div/div/div/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1aa9b29b-f0ae-4f0c-b551-b3061e4ba94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>myntraweb-sprite sort-downArrow sprites-downArrow</value>
      <webElementGuid>23783275-eabe-48ef-9a7b-768f0987537c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktopSearchResults&quot;)/div[@class=&quot;row-base&quot;]/section[@class=&quot;horizontal-filters-base horizontal-filters-hideBorder horizontal-filters-addBoxShadow&quot;]/div[1]/div[@class=&quot;horizontal-filters-sortContainer&quot;]/div[1]/div[1]/div[@class=&quot;sort-sortBy&quot;]/span[@class=&quot;myntraweb-sprite sort-downArrow sprites-downArrow&quot;]</value>
      <webElementGuid>7287e7ac-8cfd-4bfe-bd70-ba86d71a3adc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopSearchResults']/div/section/div/div/div/div/div/span[2]</value>
      <webElementGuid>cbddfe95-2801-4daa-b179-7ba193171e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/span[2]</value>
      <webElementGuid>0fcaf883-6863-47bd-a808-197f1fe16763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
