<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_STUDIO</name>
   <tag></tag>
   <elementGuidId>9d1f36ba-d2cc-4857-b9e4-8249e846470a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='redirectPageTo(&quot;/studio/home&quot;)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35a5e33e-9d87-49a0-8cc7-c93b7d53765c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-navcontent</value>
      <webElementGuid>5ffe90ad-d90b-43a7-80a8-33253c594d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectPageTo(&quot;/studio/home&quot;)</value>
      <webElementGuid>4a64773b-3c9f-4480-a329-29fe0277b6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STUDIO</value>
      <webElementGuid>c07c23c1-d232-479b-b74c-ef6095e808d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountPoint&quot;)/div[1]/div[@class=&quot;layout&quot;]/div[@class=&quot;desktop-header-container&quot;]/div[@class=&quot;desktop-navlink-container&quot;]/div[@class=&quot;desktop-navcontent&quot;]</value>
      <webElementGuid>039c64ca-7d95-4875-a26d-ca4d565b8b1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='redirectPageTo(&quot;/studio/home&quot;)']</value>
      <webElementGuid>12c5d68d-93f9-421e-a5ae-b7edf5888325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountPoint']/div/div[2]/div/div[2]/div[5]</value>
      <webElementGuid>20e5c4d6-9bbc-4ddf-8cf0-bc4e0e1ca060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME LIVING'])[1]/following::div[1]</value>
      <webElementGuid>afdc25f3-ccfe-44b6-85ed-71e090761d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIDS'])[1]/following::div[2]</value>
      <webElementGuid>e5d02b20-bb9f-4ce4-b7b0-c433096c1470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/preceding::div[1]</value>
      <webElementGuid>9d80465f-a84b-4a67-b741-ed0f21b96f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bag'])[1]/preceding::div[1]</value>
      <webElementGuid>d89694b5-7642-45de-b0c6-3a4312af3f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='STUDIO']/parent::*</value>
      <webElementGuid>97aa82a2-22c1-4a2d-b47b-27e7765bc10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
      <webElementGuid>9fd5a4ae-99a3-4e30-840a-a266af98f61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'STUDIO' or . = 'STUDIO')]</value>
      <webElementGuid>b74a7849-5848-478e-85db-37c2d9c9bc53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
