<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Men_common-radioIndicator</name>
   <tag></tag>
   <elementGuidId>e2c4758e-3bd2-40e6-8d5c-e828d595fb6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.common-radioIndicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[2]/ul/li/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9e57884-d167-4889-95f4-cd4d30c6ccef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common-radioIndicator</value>
      <webElementGuid>aa218060-98b4-4522-8fe3-8e05ce20c204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[1]/main[@class=&quot;search-base&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;search-leftContainer column-base&quot;]/section[1]/div[@class=&quot;condition-render-verticalFilters condition-render-boundary-top&quot;]/div[@class=&quot;vertical-filters-filters&quot;]/ul[@class=&quot;gender-list&quot;]/li[1]/label[@class=&quot;common-customRadio gender-label&quot;]/div[@class=&quot;common-radioIndicator&quot;]</value>
      <webElementGuid>cbfbd2e0-a4a9-4532-b63f-80fd2c6aca66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[2]/ul/li/label/div</value>
      <webElementGuid>ce30e55b-d589-49f7-b1ea-2dbf79bf9f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>59344626-bf75-4fce-869f-b718d7e99858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
