<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_T-Shirts</name>
   <tag></tag>
   <elementGuidId>efb24557-eaa4-4203-b25f-00599150f75e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[3]/div/div/div/div/li/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71b9ad80-5491-4606-9e61-6f7d148085ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kids?f=Categories%3ATshirts%3A%3AGender%3Aboys%2Cboys%20girls&amp;plaEnabled=false</value>
      <webElementGuid>02f9cbaf-dc8b-40d0-b2b4-4e373958e14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-categoryLink</value>
      <webElementGuid>50e2d22f-f9ef-46d4-87f9-a55b8dfa667c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>345</value>
      <webElementGuid>c2abb9b0-8d7a-4492-b558-18e71c00bff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T-Shirts</value>
      <webElementGuid>0b4ed393-bbce-4214-9ffd-c6f98532cb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/nav[@class=&quot;desktop-navbar&quot;]/div[@class=&quot;desktop-navLinks&quot;]/div[@class=&quot;desktop-navContent&quot;]/div[@class=&quot;desktop-navLink&quot;]/div[@class=&quot;desktop-backdropStyle&quot;]/div[@class=&quot;desktop-paneContent&quot;]/div[@class=&quot;desktop-categoryContainer&quot;]/li[@class=&quot;desktop-oddColumnContent&quot;]/ul[@class=&quot;desktop-navBlock&quot;]/li[2]/a[@class=&quot;desktop-categoryLink&quot;]</value>
      <webElementGuid>8e426401-c7e6-4893-8f39-e31bb84cc885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[3]/div/div/div/div/li/ul/li[2]/a</value>
      <webElementGuid>b14f3f0f-cfc9-4a99-be8d-c8d895da9aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'T-Shirts')])[3]</value>
      <webElementGuid>3ad05cb4-9e9e-4961-93e3-d2cbb959b71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boys Clothing'])[1]/following::a[1]</value>
      <webElementGuid>3dc2ae8b-3b27-4b4a-9ef0-460a8bad6383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kids'])[1]/following::a[2]</value>
      <webElementGuid>35e53e25-b231-4191-9f41-7214ae476ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shirts'])[1]/preceding::a[1]</value>
      <webElementGuid>d1c89d61-fadf-4a99-9d7d-2781af267146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shorts'])[2]/preceding::a[2]</value>
      <webElementGuid>d62c4458-c225-46a8-a37a-edc7a4c08b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kids?f=Categories%3ATshirts%3A%3AGender%3Aboys%2Cboys%20girls&amp;plaEnabled=false')]</value>
      <webElementGuid>ddf4b617-fd9c-4694-83f3-a90016a9d5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/li/ul/li[2]/a</value>
      <webElementGuid>42e0230e-aad7-48d4-abed-2485f73090e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kids?f=Categories%3ATshirts%3A%3AGender%3Aboys%2Cboys%20girls&amp;plaEnabled=false' and (text() = 'T-Shirts' or . = 'T-Shirts')]</value>
      <webElementGuid>4072b28f-6962-4525-82af-94bae421d3ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
