<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>89c98a82-0fd5-43eb-8632-1dba68012609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='universal-login-app-230']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Universal login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0b485e27-cd66-47f2-84e4-d138e4a10a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-230&amp;initialPath=signup&amp;sdkVersion=5.4.12</value>
      <webElementGuid>f02c9590-9e6e-4422-ad07-9482a84cf263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Universal login</value>
      <webElementGuid>a89f6644-c1fc-49c3-8158-eac4c4ae6afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>ul-app-frame</value>
      <webElementGuid>b22dc0c1-3284-4552-9e13-20a1d42e1c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2974b427-afb2-43bc-8052-5e90598479f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>f2730081-f017-4e1a-bd06-6838dabcb50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>5d4bf93c-2597-4942-b5d7-d7c83b8eb1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>a64c7cb7-a8f0-4724-98fd-0d32f5d28065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;universal-login-app-230&quot;)/iframe[1]</value>
      <webElementGuid>1e743731-6aab-43d6-803c-8962782829b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-login-app-230']/iframe</value>
      <webElementGuid>f3e3f4a3-c3d5-48ba-b6ec-a0abcfdab976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>17edbae8-9836-418b-92a2-4569bae25527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-230&amp;initialPath=signup&amp;sdkVersion=5.4.12' and @title = 'Universal login']</value>
      <webElementGuid>63b7649b-cd52-4825-aa53-92d312cf8f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-login-app-756']/iframe</value>
      <webElementGuid>70cd962a-fc21-492e-b21f-4acbe8904ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-756&amp;initialPath=signup&amp;sdkVersion=5.4.12' and @title = 'Universal login']</value>
      <webElementGuid>bf8d001b-89a8-4c09-a3bb-7122aed6ed83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-login-app-553']/iframe</value>
      <webElementGuid>7ccd13f1-da9a-4021-a996-760606f99d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-553&amp;initialPath=signup&amp;sdkVersion=5.4.12' and @title = 'Universal login']</value>
      <webElementGuid>46620596-a02e-44ad-be1e-db2afded42dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-login-app-786']/iframe</value>
      <webElementGuid>d0433457-9acb-46e7-9da2-8c3920a1294d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-786&amp;initialPath=signup&amp;sdkVersion=5.4.12' and @title = 'Universal login']</value>
      <webElementGuid>e6846411-1dfd-4d4e-81a3-1bbd6f7a6d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-login-app-838']/iframe</value>
      <webElementGuid>43ac10f9-1ba0-4e8d-b2be-19a5a67dfe0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-838&amp;initialPath=signin&amp;sdkVersion=5.4.12' and @title = 'Universal login']</value>
      <webElementGuid>eeabd9d3-ff80-43f0-b55b-fd14f3a46250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-login-app-650']/iframe</value>
      <webElementGuid>ce04c7c3-4165-4310-9b6f-91266204af22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/en-us/ul/login?appId=dictator&amp;rpcId=dictator-%23universal-login-app-650&amp;initialPath=signin&amp;sdkVersion=5.4.12' and @title = 'Universal login']</value>
      <webElementGuid>e3a72b46-1e0a-44f8-aace-a15638ab4717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
