<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MOBILE</name>
   <tag></tag>
   <elementGuidId>08eff940-3cc9-4e7b-9931-55d8364ba861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div/div/ul/li[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-fznZeY.dzZFTs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f955807-5823-498a-9899-7aaaa3287fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>phone_tab</value>
      <webElementGuid>fe4c4b05-70ee-4cf9-8da5-cf5c63d664ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fznZeY dzZFTs</value>
      <webElementGuid>8e16936c-6c23-4563-aa08-47a7b5016cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MOBILE</value>
      <webElementGuid>dc8e137a-2f4c-46c0-9d08-58b30797552b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sc-AxgMl mXdik fade-in-enter-done&quot;]/div[@class=&quot;sc-AxgMl gfGIVK&quot;]/div[@class=&quot;sc-AxgMl bdRmbW&quot;]/div[@class=&quot;sc-AxhUy jtMJCi&quot;]/div[@class=&quot;sc-AxhCb jIcqRC&quot;]/div[@class=&quot;sc-pzMyG flrnRv&quot;]/ul[@class=&quot;sc-fzoCCn fyVkRs&quot;]/li[@class=&quot;sc-fzoPby jaRkAE&quot;]/div[@class=&quot;sc-AxgMl eUtsRt&quot;]/span[@class=&quot;sc-fznZeY dzZFTs&quot;]</value>
      <webElementGuid>6a27eb7c-e635-443c-9ad2-fa7642be9c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Agoda/Page_/iframe</value>
      <webElementGuid>c54ac538-f392-48ef-a337-70575668579f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/ul/li[2]/div/span</value>
      <webElementGuid>e06e2048-fb92-4512-a29d-3415ff2411a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMAIL'])[1]/following::span[1]</value>
      <webElementGuid>dfc36d85-2147-4e67-a3ec-83a08323c7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For security, please sign in to access your information'])[1]/following::span[2]</value>
      <webElementGuid>dbb68303-f051-4b80-b844-18113314a7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::span[1]</value>
      <webElementGuid>03aea23d-1b6d-40e1-871f-649b48f9a1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::span[2]</value>
      <webElementGuid>f1151927-0924-461e-ac89-67ea256ad631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MOBILE']/parent::*</value>
      <webElementGuid>65ef9d58-5bdc-48be-8918-9186ecca432d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/span</value>
      <webElementGuid>f20a49e4-ff07-4b94-a12f-4984c4f6a699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MOBILE' or . = 'MOBILE')]</value>
      <webElementGuid>9f4fa5f7-e3d5-4fb2-8d20-833fc6f247dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
