<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bangkok_field-input</name>
   <tag></tag>
   <elementGuidId>4f8cb8d8-f979-4ae8-bb92-879319b75e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/div/div[2]/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.field-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>863698d0-feef-41b6-8203-286bc92ed243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-input</value>
      <webElementGuid>65e480a0-2836-41ae-9148-de7ac3799b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bangkok</value>
      <webElementGuid>75ecb890-74be-4bb8-9d15-9663c49440c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;wrapper-content&quot;]/div[@class=&quot;page-home&quot;]/div[@class=&quot;home-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;vue-search-form&quot;]/div[@class=&quot;vue-search-form-group places&quot;]/div[@class=&quot;vue-search-form-group-field&quot;]/div[@class=&quot;field-select-wrapper&quot;]/div[@class=&quot;vue-modal dropdown full-height&quot;]/div[@class=&quot;vue-modal-box&quot;]/div[@class=&quot;vue-modal-content&quot;]/div[@class=&quot;vue-modal-content-header&quot;]/div[@class=&quot;field-select-header&quot;]/div[@class=&quot;input-wrapper&quot;]/input[@class=&quot;field-input&quot;]</value>
      <webElementGuid>63e46b56-ee16-4983-bf41-468e006b7f57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div[2]/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>a82ded60-df00-4cea-87e0-77b351253079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>229eaf09-d641-4333-b3df-c5cf84e0d2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Bangkok']</value>
      <webElementGuid>2a2b41ca-71c9-489b-91ca-5dfabec720bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
