<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_login  Signup</name>
   <tag></tag>
   <elementGuidId>c8a9c062-2c66-4092-bdcd-0ff63d71969e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.desktop-linkButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f5b99c1-fb55-44e7-9496-02a9c4f868ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refreshpage</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ccc4f98-bb88-419d-a016-74f633ade6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login?referer=https://www.myntra.com/</value>
      <webElementGuid>c0cfe29c-659f-43c2-8370-893220f9c491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>1ada9a90-70a4-4dd4-8bc9-44ed5e0ed7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-linkButton</value>
      <webElementGuid>816e0274-791c-409c-a41e-43367d00ee84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>865</value>
      <webElementGuid>16303ebc-bd4d-4c50-8eab-0e7a077e8e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>login / Signup</value>
      <webElementGuid>0f0b772e-e732-445a-95c6-af3502c56c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-actions&quot;]/div[@class=&quot;desktop-user&quot;]/div[@class=&quot;desktop-userActions&quot;]/div[@class=&quot;desktop-userActionsContent&quot;]/div[2]/div[@class=&quot;desktop-getUserInLinks desktop-getInLinks&quot;]/a[@class=&quot;desktop-linkButton&quot;]</value>
      <webElementGuid>f1677cec-33a3-412e-82f8-512a60aff5a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/a</value>
      <webElementGuid>c9e9a3ee-a99c-4823-9b13-ec675cd7bfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'login / Signup')]</value>
      <webElementGuid>b7e290da-fe00-499b-809b-5e23b2c1fc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To access account and manage orders'])[1]/following::a[1]</value>
      <webElementGuid>56e1c1ea-c00f-4ed6-9f29-f8c251ec4b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/following::a[1]</value>
      <webElementGuid>95328bef-e2d3-4cb2-9176-774d9de410e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::a[1]</value>
      <webElementGuid>e6a203a6-7598-407c-87f8-f543006b526a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/preceding::a[2]</value>
      <webElementGuid>0a8a9c2e-2d8e-442e-a1db-1c3570f53aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='login / Signup']/parent::*</value>
      <webElementGuid>e448bd0f-a954-4cf6-a932-942b62750a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login?referer=https://www.myntra.com/')]</value>
      <webElementGuid>aea95044-28f0-43f5-af1c-092a777a8d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>8df977f7-62ca-4805-8045-c05830662d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login?referer=https://www.myntra.com/' and (text() = 'login / Signup' or . = 'login / Signup')]</value>
      <webElementGuid>9f77c314-723c-4116-8cf4-2f6d04ef8c64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
