<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>1086cad3-b22a-4ee2-b19e-3db7e14039d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-aXZVg.sc-gEvEer.dWLwvR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61701ffd-988a-4007-984c-aded73f586a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>765d644b-65ed-4e42-9da5-06e6072ac518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>activities-error-button</value>
      <webElementGuid>d7bd3a09-c9fb-4703-965f-b5f16bb48dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-aXZVg sc-gEvEer  dWLwvR</value>
      <webElementGuid>47777b38-3f9b-4a2b-9180-a9707de2fb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>18139887-6cd9-4657-a1f4-08ae60e99c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome no-js&quot;]/body[@class=&quot;desktop ltr themed theme-agoda&quot;]/div[14]/div[@class=&quot;Modalstyled__Dialog-sc-1gd4uo9-0 hVLJbK&quot;]/div[@class=&quot;Modalstyled__Backdrop-sc-1gd4uo9-2 jvjPVy&quot;]/div[@class=&quot;Modalstyled__ContentContainer-sc-1gd4uo9-3 hSPnAM&quot;]/div[@class=&quot;sc-aXZVg sc-gEvEer fhDIKt hVBTJt sc-fUnMCh&quot;]/button[@class=&quot;sc-aXZVg sc-gEvEer  dWLwvR&quot;]</value>
      <webElementGuid>53d59232-9ab9-4e61-a469-c8335ce831cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>20a4411b-50d0-425b-b2e9-b6751b40cede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::button[1]</value>
      <webElementGuid>f6d09257-7eec-4b11-9da5-84549d58482f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agoda is part of Booking Holdings Inc., the world leader in online travel &amp; related services.'])[1]/following::button[1]</value>
      <webElementGuid>5d031299-0a00-4230-8dc7-dce3bd642438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/button</value>
      <webElementGuid>6f5254a3-6250-45a6-9e36-b25c1be19d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>0db9e089-4ce9-40f5-8489-df0d4959657f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
