<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add a flight</name>
   <tag></tag>
   <elementGuidId>4b51fa77-3aae-42d9-8269-2d62ff312ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBwQ.sc-gsTCUz.cEsCWA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d58f8be-43cb-4fa2-bb5e-dd1da2f89945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44118ca2-df0a-44f3-a024-7a7a0b1a29af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBwQ sc-gsTCUz  cEsCWA</value>
      <webElementGuid>b9c16fee-6caf-46e5-a4c0-e36fe1dae12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add a flight</value>
      <webElementGuid>9c035845-8bb1-494f-80c5-bef880bd0cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBoxContainer&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 bpOVsR TabContent OpaqueBackground&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 iUzCAZ&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 zsLYh&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 ipmIzQ&quot;]/button[@class=&quot;sc-bdfBwQ sc-gsTCUz  cEsCWA&quot;]</value>
      <webElementGuid>22392fbf-0c27-48b4-8c41-b10b7a680acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>f83fdf3e-7c2f-4445-bf70-51deacdfdb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBoxContainer']/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>6bccd1ae-7065-4c26-adc7-f4d09b0f4732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friday'])[1]/following::button[1]</value>
      <webElementGuid>9c483ff8-ad0d-42e7-874e-5370babc3d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday'])[1]/following::button[1]</value>
      <webElementGuid>8ed92d71-cb28-4ff1-8bce-943f6d3abaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH'])[1]/preceding::button[1]</value>
      <webElementGuid>312528ee-9c20-4aed-bfef-aba19fd6219e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>5223cca6-9f98-4715-8da7-89ab306f36a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add a flight' or . = 'Add a flight')]</value>
      <webElementGuid>bc1d88e9-7f7c-4197-b219-94d762c554b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
