<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove</name>
   <tag></tag>
   <elementGuidId>d8e818ef-b33b-4bac-96f5-b139f7303d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBwQ.sc-gsTCUz.cEsCWA.Box-sc-kv6pi1-0.SBfnJ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bcf7786-00be-4b3b-8b82-fe0443fd8271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f1621cd-6b78-41dd-bf70-7e8d8c3a3b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>multi-product-remove-flight-button</value>
      <webElementGuid>747b38dc-e3b3-4e17-8738-793170d6cf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBwQ sc-gsTCUz  cEsCWA Box-sc-kv6pi1-0 SBfnJ</value>
      <webElementGuid>2bf61f70-3ee0-4b26-b7c6-b6c7601442ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>ed75eaa6-76d8-4e8e-91bc-f6c44291de1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBoxContainer&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 bpOVsR TabContent OpaqueBackground&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 iUzCAZ&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 iHPqpm&quot;]/button[@class=&quot;sc-bdfBwQ sc-gsTCUz  cEsCWA Box-sc-kv6pi1-0 SBfnJ&quot;]</value>
      <webElementGuid>95ee3ced-13b0-47d2-8fee-907aed1f24da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>75664e9e-5762-4e52-867c-4e92a8ff48b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBoxContainer']/div/div/div[3]/div/div/button</value>
      <webElementGuid>8d37dd8c-2ce2-4f1b-b604-0aa0a1ed809e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight'])[1]/following::button[1]</value>
      <webElementGuid>fe637de2-c255-4582-970f-1ded8b24ddaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friday'])[1]/following::button[1]</value>
      <webElementGuid>f0a96b45-ea64-4c94-ab74-5cda906fa81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH'])[1]/preceding::button[1]</value>
      <webElementGuid>4f0a08bc-10a1-4604-994f-9525e9bb9d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>95e0670f-42cb-48d8-a7bb-879dca8f243e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>6a6d4d4d-96de-43a6-bd6d-dc1b9ad66881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
