<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filters</name>
   <tag></tag>
   <elementGuidId>735e3ee5-4e6c-47c2-b9db-e1f9251fd81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div[2]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-aXZVg.sc-gEvEer.gpDNjt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2119a068-1cfe-43c9-90d3-6fc39c120e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15428200-fd52-48e3-8a9c-636cef08bd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Filter and Sort</value>
      <webElementGuid>484768c6-5fdb-4ce5-b7e3-cdd6f4e39f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>activities-sort-and-filter-open-button</value>
      <webElementGuid>0c8acd6c-0293-4e60-abde-de6a63702046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-aXZVg sc-gEvEer  gpDNjt</value>
      <webElementGuid>85c63cc1-ea1a-4ef3-b251-c449d41b8e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>495f5725-15eb-49bb-9091-e34ed6ffc04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;Layout Layout__siteWrapper&quot;]/div[@class=&quot;PageTransition PageTransition__leftMenu&quot;]/div[@class=&quot;sc-aXZVg sc-gEvEer  jZyPkn sc-fUnMCh sc-fxwrCY bVLBCp&quot;]/div[@class=&quot;sc-aXZVg sc-gEvEer  jmBxSJ sc-ddjGPC jebvCg&quot;]/div[@class=&quot;sc-aXZVg sc-gEvEer  ipGSnv&quot;]/button[@class=&quot;sc-aXZVg sc-gEvEer  gpDNjt&quot;]</value>
      <webElementGuid>e939fa2c-bd83-44e3-b518-0a08760f8c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>bd76e18c-0f4c-4278-8705-ac687ae6ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List your place'])[1]/following::button[6]</value>
      <webElementGuid>aaaba71e-7f94-4b2d-a135-0b4771e2b033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::button[7]</value>
      <webElementGuid>6f118f6d-6e62-411d-971f-b5be59e4c82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[24/48/72-Hr] Tokyo Subway Ticket | Japan'])[1]/preceding::button[11]</value>
      <webElementGuid>de2437fd-52e7-4ab5-93f9-694c409d8bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>cdd3e0ca-3e9a-4858-b13f-85d2d1606d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>f538bf5b-4627-42b3-b722-403188d6490d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
