<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Day Use Stays</name>
   <tag></tag>
   <elementGuidId>9a3c97cf-df8a-4ea2-a1ed-cb573517646d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBwQ.sc-gsTCUz.hWygYf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8119c6a2-ff36-4af8-920f-975356a5f590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fdacc0d2-b1d9-41b6-9429-beb12450241f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf9a0817-ad4e-47ef-8989-be3100d3e8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Day Use Stays</value>
      <webElementGuid>ae3e8832-f11a-4573-a5ec-9a8ce99fc4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>funnel-switcher</value>
      <webElementGuid>2548c49b-0849-404b-bbfc-da585e7a7ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hh-booking-duration-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d7eb8746-ceb8-4920-a62e-3814d02e0177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBwQ sc-gsTCUz  hWygYf</value>
      <webElementGuid>bf07810c-2c3b-4549-8f6c-65278ba4ed46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Day Use Stays</value>
      <webElementGuid>e062a01d-8241-431e-a96c-cb54a22a648e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;funnel-toggles-container&quot;)/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  juRSWL&quot;]/button[@class=&quot;sc-bdfBwQ sc-gsTCUz  hWygYf&quot;]</value>
      <webElementGuid>23c97f80-8a99-4bbc-acf3-75d57324cdfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>b9059577-748e-4d29-a895-8da3e9f2035a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='funnel-toggles-container']/div[2]/button</value>
      <webElementGuid>fb004e4e-9dc0-4112-898f-e396551a2211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overnight Stays'])[1]/following::button[1]</value>
      <webElementGuid>d211264e-ff42-4c52-a507-c317f36e2342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airport transfer'])[2]/following::button[2]</value>
      <webElementGuid>bde71f76-e5ec-44a7-8bc4-ad8cb90dd3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday'])[1]/preceding::button[1]</value>
      <webElementGuid>eb48d29a-2618-455a-8b83-3d8ad978b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>fe90d9b7-0794-4198-a351-cd6c073d875a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Day Use Stays' or . = 'Day Use Stays')]</value>
      <webElementGuid>c30891d2-7923-4818-92ce-725547e805a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
