<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hyderabad (2,735)sightseeing, restaurants</name>
   <tag></tag>
   <elementGuidId>88c0b807-4ee6-411a-ad8c-6ee8dd4e943c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='destination_suggestion_card']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#destination_suggestion_card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>654a987f-dad7-40a9-8127-96d205b286d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87423580-67fb-4f37-b5b7-9097fa85fd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destination_suggestion_card</value>
      <webElementGuid>f9e009ce-fcdd-40f4-9366-19c988c9d035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>web-autosuggest-domestic-cities-default</value>
      <webElementGuid>f51cdacf-e0a3-460a-a5f1-9a8caae2e1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-object-id</name>
      <type>Main</type>
      <value>8801</value>
      <webElementGuid>d92df63f-2903-45c8-98b0-eb630e740529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-place-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ef81c081-bf03-46cc-93fe-23c8a63b0b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-search-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>877450b7-51b6-44e1-a53e-be9a8111df15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-value</name>
      <type>Main</type>
      <value>Hyderabad</value>
      <webElementGuid>1d2fcdb7-db26-49e8-a310-910085ce2e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-place-suggestion-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1df8f10-c613-4084-ac79-b96d0da42447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selenium</name>
      <type>Main</type>
      <value>autosuggest-item</value>
      <webElementGuid>aaa8c25a-d23b-422f-b750-22239726c85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBwQ sc-gsTCUz  eBzHfu</value>
      <webElementGuid>ca213b29-14eb-44ce-8285-d78d4d4a79bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hyderabad (2,735)sightseeing, restaurants</value>
      <webElementGuid>7c4f06c3-2245-4840-918c-d82b77d3e9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBoxContainer&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 cVUuHz TabContent OpaqueBackground&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 iloTzf&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu&quot;]/div[@class=&quot;Searchbox Searchbox--vertical&quot;]/div[@class=&quot;Searchbox__wrapper&quot;]/div[@class=&quot;Popup__container Popup__container--garage-door&quot;]/div[@class=&quot;Popup Autocomplete Autocomplete--with-dayuse Autocomplete--dayuse&quot;]/div[@class=&quot;Popup__content&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  hwyJDv&quot;]/div[@class=&quot;sc-jcVebW eaVLBn&quot;]/div[@class=&quot;sc-citwmv hqckCL&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  FhpVK&quot;]/div[@class=&quot;sc-jcVebW flXTBg&quot;]/div[@class=&quot;sc-citwmv hUzAlA&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  hwyJDv&quot;]/div[@class=&quot;sc-jcVebW flXTBg&quot;]/div[@class=&quot;sc-citwmv fPFUSM&quot;]/button[@id=&quot;destination_suggestion_card&quot;]</value>
      <webElementGuid>0813cc4b-aa96-4a63-9fb1-d6ff8ca7919a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='destination_suggestion_card']</value>
      <webElementGuid>eace7cf9-5b40-4ad8-946d-0863b369a49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBoxContainer']/div/div/div[2]/div/div/div[5]/div/div/div/div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>2fcb855b-50f2-497a-9bf5-cf38d4642afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day Use Stays'])[2]/following::button[1]</value>
      <webElementGuid>6fb49559-a3d6-4d42-9c5e-c7843c069afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH'])[1]/preceding::button[9]</value>
      <webElementGuid>13698bb5-4365-4fe6-96e6-caa7495337e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top destinations in India'])[1]/preceding::button[10]</value>
      <webElementGuid>ba10f0a4-4f8c-41a9-ac17-184950333a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>cfb440f6-dc5c-4bf5-b5b7-c42ab279359a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'destination_suggestion_card' and (text() = 'Hyderabad (2,735)sightseeing, restaurants' or . = 'Hyderabad (2,735)sightseeing, restaurants')]</value>
      <webElementGuid>5de480f2-f69c-4312-a531-ceedeaa56b9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
