<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEARCH FLIGHT  HOTEL</name>
   <tag></tag>
   <elementGuidId>c8ebde64-cbb2-4d87-883e-ffcfe3a68c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabpanel-packages-tab']/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Buttonstyled__ButtonStyled-sc-5gjk6l-0.iCZpGI.Box-sc-kv6pi1-0.fDMIuA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>307dbc09-8bce-48db-9f2f-9cbce0b268e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>radius</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>aae84a5e-9b0d-4b7e-a853-3da06ea5af15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selenium</name>
      <type>Main</type>
      <value>modifySearchButton</value>
      <webElementGuid>9ac44858-dfc4-47ec-8dc8-454d4e282827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>packages-search-button</value>
      <webElementGuid>8f7060cb-fdac-44cd-95b3-706471c46e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>flight-search-button</value>
      <webElementGuid>61c763dd-b407-4e91-a6d4-2b9cbff292c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttonstyled__ButtonStyled-sc-5gjk6l-0 iCZpGI Box-sc-kv6pi1-0 fDMIuA</value>
      <webElementGuid>88a3e9a9-dcb1-4e31-bb47-90ca150282d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>1554074e-492e-433f-aae3-815420d7e05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH FLIGHT + HOTEL</value>
      <webElementGuid>28c445ca-0a01-40e3-a4f9-094b1152590f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabpanel-packages-tab&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu TabContent__Search--button&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  gvomHg&quot;]/button[@class=&quot;Buttonstyled__ButtonStyled-sc-5gjk6l-0 iCZpGI Box-sc-kv6pi1-0 fDMIuA&quot;]</value>
      <webElementGuid>7abf3781-e4a2-452c-bd36-59665b1f83d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-packages-tab']/div[2]/div/button</value>
      <webElementGuid>0ee675f0-d1f9-4807-aaae-4d02f3ed6a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for hotel in different cities or dates'])[1]/following::button[1]</value>
      <webElementGuid>c583ebb1-b1dc-47f7-9ba7-eb66e3ba8cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[2]/following::button[1]</value>
      <webElementGuid>13db5fb4-6bc1-4c91-9208-519b93ea6771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top destinations in India'])[1]/preceding::button[1]</value>
      <webElementGuid>5ac1c03a-6924-4ae9-a012-c2f17de6541c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>12ce4b1e-7400-4a72-aa20-e0db8fd51bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SEARCH FLIGHT + HOTEL' or . = 'SEARCH FLIGHT + HOTEL')]</value>
      <webElementGuid>5fe7da98-4636-42c8-b168-9db685a66c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
