<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_sg-pc-6f-acm-web-user-fd47b7d94-wngv_f5b609</name>
   <tag></tag>
   <elementGuidId>b72aee28-102c-4855-a391-5b8c9e97ef2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6g-acm-web-user-b5d8754b6-4wcnq'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ab-close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46685789-b89c-4173-a910-4da1f4f5a9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Message</value>
      <webElementGuid>7d987599-b548-412a-ba64-c877728cb656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d2b401f-7e43-4535-a9e9-321e94f5bc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21620ca1-9b82-420d-a44b-633097eabaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ab-close-button</value>
      <webElementGuid>aeaaa843-be92-4c9e-b50f-6c10832440d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome no-js&quot;]/body[@class=&quot;newhome desktop JTBFUN-1062 SKYWL-3850 ltr themed theme-agoda window-loaded ab-pause-scrolling&quot;]/div[@class=&quot;ab-iam-root v3 ab-animate-in ab-animate-out ab-effect-modal ab-show&quot;]/div[@class=&quot;ab-in-app-message  ab-background ab-modal-interactions ab-modal ab-centered&quot;]/button[@class=&quot;ab-close-button&quot;]</value>
      <webElementGuid>882220cb-329d-44a5-b7e6-f2c3bbea40a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6g-acm-web-user-b5d8754b6-4wcnq'])[1]/following::button[1]</value>
      <webElementGuid>d589eb20-d8f4-4d01-9008-967678ff550e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/button</value>
      <webElementGuid>934a32ed-8e7c-4fda-a661-9aaa622c26e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-wj6wz'])[1]/following::button[1]</value>
      <webElementGuid>a1fc3001-3692-4b32-9c82-4bea0a399f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-6cgrn'])[1]/following::button[1]</value>
      <webElementGuid>96e4e7f7-48e6-4e11-a80b-41f5f80d88e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-mk97z'])[1]/following::button[1]</value>
      <webElementGuid>e69cf193-f1b2-42d6-8522-349d2c76f05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-7lfqh'])[1]/following::button[1]</value>
      <webElementGuid>7a9bb421-f51b-4dd6-9f95-78b0dcec35b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-vk74k'])[1]/following::button[1]</value>
      <webElementGuid>8470b6c6-f528-4987-ae4c-8048b9a10a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-pm5zr'])[1]/following::button[1]</value>
      <webElementGuid>b0476b79-852e-42f0-a468-3555b6ad88a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-xkk7h'])[1]/following::button[1]</value>
      <webElementGuid>a66f68a1-5c1c-413c-86fc-24892108bbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-ccqhn'])[1]/following::button[1]</value>
      <webElementGuid>07a837e3-0f91-4f74-b621-90ff8f8004f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6g-acm-web-user-b5d8754b6-92lt9'])[1]/following::button[1]</value>
      <webElementGuid>15f23470-96a1-4310-9e5f-1c08e9c74832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-jtvz5'])[1]/following::button[1]</value>
      <webElementGuid>45e6edcf-8415-4170-bfd1-c37833e957ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dear valued customer, we got more deals for you!'])[1]/preceding::button[1]</value>
      <webElementGuid>fc22f70d-715a-4658-98b5-a336121546fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Take me there!'])[1]/preceding::button[1]</value>
      <webElementGuid>b101af1d-a4c2-414c-9ac8-b444633d3c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/button</value>
      <webElementGuid>2ff8faf5-536e-4c05-a570-0d4c47b19323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6g-acm-web-user-b5d8754b6-p24hw'])[1]/following::button[1]</value>
      <webElementGuid>7b1818fa-d524-45fb-8ed5-9a65429a611c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-gk9h2'])[1]/following::button[1]</value>
      <webElementGuid>4b1d336a-1153-4298-b6bb-a86b9b71fb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sg-pc-6f-acm-web-user-fd47b7d94-wngvs'])[1]/following::button[1]</value>
      <webElementGuid>2b7326c2-5879-4720-a2a8-d0a59288be2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
