<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>462250a2-2055-49a4-970d-b222f7c799f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/section/div[2]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Buttonstyled__ButtonStyled-sc-5gjk6l-0.liQkpl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e184c829-2168-4112-9c0a-8734d42d169b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>radius</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>b03dd7a8-d082-4ead-a0c1-f5324851a987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>sign-in-button</value>
      <webElementGuid>b952ec11-b037-49c0-9f1f-85d5224b91a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d63c642c-a2e4-4140-8d50-dac400d0cbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttonstyled__ButtonStyled-sc-5gjk6l-0 liQkpl</value>
      <webElementGuid>03786fd5-5b39-4031-b28d-b9082bfb0963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>929a1004-a4c7-4cd3-be51-6de2a0296f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/section[@class=&quot;Headerstyled__HeaderSection-sc-vtperc-0 disNST&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 Headerstyled__RightContainer-sc-vtperc-1 hfsWAU bbgjzZ&quot;]/div[@class=&quot;ActionBarstyled__ActionBarStyled-sc-1ozl0pn-0 jgWVkG&quot;]/div[@class=&quot;ActionItemParentstyled__ActionItemParentStyled-sc-1lr3ueg-0 bNmljX&quot;]/div[@class=&quot;ActionItemstyled__ActionItemStyled-sc-18hov6g-0 keocCM&quot;]/button[@class=&quot;Buttonstyled__ButtonStyled-sc-5gjk6l-0 liQkpl&quot;]</value>
      <webElementGuid>00ca5996-3662-48d1-afd0-cd20855a5c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/section/div[2]/div/div/div[2]/button</value>
      <webElementGuid>67a17f6a-e367-45ea-acec-7d5e2c8024fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create account'])[1]/following::button[1]</value>
      <webElementGuid>b568950d-caf8-456c-b38e-c33422b65d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transport'])[1]/following::button[2]</value>
      <webElementGuid>4664a9d1-438f-46cd-98b1-d27ac30619a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List your place'])[1]/preceding::button[1]</value>
      <webElementGuid>1b17d947-2afb-4a4e-8909-ba5d3fe8cede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>ddf652fa-b397-4ef2-ace5-072296a4e58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>4f170c62-faa4-4944-bbac-14543f3edfbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
