<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search for hotel in different cities or dates</name>
   <tag></tag>
   <elementGuidId>67f17745-363d-4437-b295-c85924ad1045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabpanel-packages-tab']/div/div/div/div/div[3]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Box-sc-kv6pi1-0.bNdiTk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a5248b3-37aa-482d-a984-256f3c1c712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-kv6pi1-0 bNdiTk</value>
      <webElementGuid>d8811de3-c361-4fb5-b8cc-053fb6001315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search for hotel in different cities or dates</value>
      <webElementGuid>e252c264-38f9-46f2-b0cd-fbe81c7ec0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabpanel-packages-tab&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 cVUuHz TabContent OpaqueBackground&quot;]/div[@class=&quot;PackageSearchContainer&quot;]/div[@class=&quot;FlightSearchContainer FlightSearchContainer--vertical&quot;]/div[@class=&quot;FlightSearchContainer__Wrapper&quot;]/div[@class=&quot;FlightSearchContainer__Row&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 iRpuHF CheckBoxWithBadge__Container CheckBoxWithBadge__Container--tab&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 bNdiTk&quot;]</value>
      <webElementGuid>3a2e44db-87ea-41c4-852e-452d19677821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabpanel-packages-tab']/div/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>217d32ea-a83a-400c-8890-ec44591332fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[2]/following::div[17]</value>
      <webElementGuid>be4e1b96-22b8-4635-9f5e-468ba2af3db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/following::div[18]</value>
      <webElementGuid>24c53a38-93ce-43da-bfad-b2eae2bdf56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH FLIGHT + HOTEL'])[1]/preceding::div[1]</value>
      <webElementGuid>044611ce-bbae-4a9c-b08d-dcfefbb57ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>9d07c9fe-7e13-4c18-b094-3939b40fc445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Search for hotel in different cities or dates' or . = 'Search for hotel in different cities or dates')]</value>
      <webElementGuid>7c28d5db-d675-444b-8350-4b29596e2b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
