<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Private stays</name>
   <tag></tag>
   <elementGuidId>efc68a37-5283-41aa-b19c-fba943373829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tab-home']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Box-sc-kv6pi1-0.iPYCUf.LinkComponent__Label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc20ea41-5ef1-41ae-b3c8-c0db1dab50f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-kv6pi1-0 iPYCUf LinkComponent__Label</value>
      <webElementGuid>96ddcb52-57f0-4327-b6d8-eedb2f01ba99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Private stays</value>
      <webElementGuid>21667982-eaf5-4d72-be40-2765993d8bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-home&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 iPYCUf LinkComponent__Label&quot;]</value>
      <webElementGuid>7b0bc626-778c-49bd-8466-0cfa15258184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tab-home']/div</value>
      <webElementGuid>8aa25b84-f33f-436d-8cb3-10e80fc2e441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels &amp; Homes'])[2]/following::div[2]</value>
      <webElementGuid>68e60bab-da44-4859-b45b-0ddc16a663e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::div[12]</value>
      <webElementGuid>40de6bda-d995-41db-9559-161a3c25898a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight + Hotel'])[2]/preceding::div[3]</value>
      <webElementGuid>6d2cb381-0b00-4853-a4c0-46988120d0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div</value>
      <webElementGuid>756cc97a-53fe-46c1-9700-7d2774977d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Private stays' or . = 'Private stays')]</value>
      <webElementGuid>ff4b3841-f9f2-4615-af85-8ef0dadee66f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
