<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 Room</name>
   <tag></tag>
   <elementGuidId>d54e1e18-242f-4309-a836-9a5d534aa1b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='room-occupancy']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.SearchBoxTextDescription.RoomOccupancy__Description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbcde7f8-78e5-475f-9f35-18277ece355a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>room-occupancy</value>
      <webElementGuid>3025cfe0-fb89-43a2-921a-cb753f2d07f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBoxTextDescription RoomOccupancy__Description</value>
      <webElementGuid>781ec93e-a13c-4761-ba6b-a0b7dc3d6307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Room</value>
      <webElementGuid>21b57b37-2cf5-4392-8542-2b393f0f71ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;room-occupancy&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu IconBox__wrapper&quot;]/div[@class=&quot;IconBox__child&quot;]/div[@class=&quot;SearchBoxTextDescription RoomOccupancy__Description&quot;]</value>
      <webElementGuid>b3d0c580-a929-4337-b68a-3f90369fb59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='room-occupancy']/div/div/div</value>
      <webElementGuid>f1db7ad8-e76d-4fc9-a658-e9b05a99443b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infants (below 2yrs)'])[1]/following::div[7]</value>
      <webElementGuid>91415c4c-6d7d-486d-8ed0-d3a1f0575238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for hotel in different cities or dates'])[1]/preceding::div[2]</value>
      <webElementGuid>f7f00f4d-43c5-428a-87a8-f09ec87c51f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH FLIGHT + HOTEL'])[1]/preceding::div[5]</value>
      <webElementGuid>7cc9aa21-3e57-4f35-b681-6b9db5a6f7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>fd55b038-99ab-4e87-a945-5fe3e7aad1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1 Room' or . = '1 Room')]</value>
      <webElementGuid>54b869e9-78f7-4361-ba9e-0c49c2f43660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
