<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_sg-pc-6f-acm-web-user-fd47b7d94-jtvz5_fic_addda6</name>
   <tag></tag>
   <elementGuidId>092b83a4-f75a-4453-8d11-a70f30ad2e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ficon.ficon-20.ficon-x-icon.ReactModal__close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>de0628c8-2dbe-4fd0-8f11-cde808b61a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ficon ficon-20 ficon-x-icon ReactModal__close-button</value>
      <webElementGuid>dac855c9-07d8-404c-a5a6-9e1d1568bac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome no-js&quot;]/body[@class=&quot;newhome desktop FUSIONFE-3431 JTBFUN-1062 SKYWL-3850 ltr themed theme-agoda window-loaded ReactModal__Body--noscroll&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open ReactModal__Overlay--transition&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open ReactModal__Content--no-outline ReactModal__Content--header-modal&quot;]/button[1]/i[@class=&quot;ficon ficon-20 ficon-x-icon ReactModal__close-button&quot;]</value>
      <webElementGuid>8ebee5de-baf2-43e7-9001-a927e24cc08c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>cb402de1-3417-4d72-b956-4120d415ee24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
