<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day Use Stays_textInput</name>
   <tag></tag>
   <elementGuidId>500fed99-8ef8-43a4-a79c-1aa676868dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>060ffef6-39db-42dd-b3b7-dee076700f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter a destination or property</value>
      <webElementGuid>eb4e889f-ad65-479b-a244-3cc303fa7409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>cd0aa1f6-eb23-4e38-abdf-99c94e456c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>31c6718b-559a-4673-9c10-09a4c09dbe75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selenium</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>b1bd1f6e-268f-4d84-9f22-fe602eaa88c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>856fa18c-48d5-47a2-8056-7a287d6d4fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d7f0727-f42a-45cf-b6d9-9daa2835379e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBoxTextEditor SearchBoxTextEditor--autocomplete</value>
      <webElementGuid>cedbfbcf-9399-41f3-a7d9-8bc42fb9eee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a destination or property</value>
      <webElementGuid>98e29dfc-f638-4edb-aa10-8b2a3525005e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>2feade18-e56a-4cf3-97a7-2f5d76cdaa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textInput&quot;)</value>
      <webElementGuid>c99fd6ef-524c-45aa-bc29-3bfb279e3eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textInput']</value>
      <webElementGuid>9091bc48-6227-4717-8f49-c8bfe1b54910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autocomplete-box']/div/div/input</value>
      <webElementGuid>04579952-d18d-4de8-a2a3-845347fa60f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>38d6d7d9-4522-4648-810d-fcca7eb9e2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter a destination or property' and @id = 'textInput']</value>
      <webElementGuid>2fcfb829-701b-4f1a-8bb9-42ae3328ccee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
