<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_TokyoJapanCity</name>
   <tag></tag>
   <elementGuidId>ddc61254-d524-4543-abfe-2e962f333576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autocompleteSearch']/div/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.Suggestion.LocationSearch.Suggestion__categoryName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8a808128-a61e-4fc7-a98a-655e99540046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Suggestion LocationSearch Suggestion__categoryName</value>
      <webElementGuid>2f5acd5b-3ffd-49e9-a90a-ddb9f38a442e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f4c12a7-3358-4dba-a4da-8229f0b1e8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selenium</name>
      <type>Main</type>
      <value>topDestinationListItem</value>
      <webElementGuid>5cdcca69-709d-442a-83be-1a369d23a251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Tokyo</value>
      <webElementGuid>3487a1e2-6686-4c73-8576-34fdf162b94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43d47c0d-44a8-4dd0-8825-8bf1f361d5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-objectid</name>
      <type>Main</type>
      <value>5085</value>
      <webElementGuid>59a7469c-9446-4cd7-a553-13d4fe0dfd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-object-id</name>
      <type>Main</type>
      <value>5085</value>
      <webElementGuid>e5425d0e-0ece-420d-a62b-8c12f9a82fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-place-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9bede673-2c69-47e0-beb3-29e97330a800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-value</name>
      <type>Main</type>
      <value>Tokyo</value>
      <webElementGuid>57a7536a-65d9-4f54-8d47-3913eae4d891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4a1bcb33-259f-4636-8ac1-9add4365a37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>icon Tokyo, Japan (City)</value>
      <webElementGuid>3f901769-bcf0-43b6-be9d-e4586e17b37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07de3512-30ee-4751-9522-e77518421d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TokyoJapanCity</value>
      <webElementGuid>d0f3b13d-4a21-4709-a032-52f031721779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocompleteSearch&quot;)/div[@class=&quot;Popup AutocompleteSearch__Popup AutocompleteSearch__Popup--ActivitiesRecentSearchPopup SearchBoxContainer--ImproveTextSearch&quot;]/div[@class=&quot;Popup__content&quot;]/ul[@class=&quot;AutocompleteList AutocompleteSearch__AutocompleteList&quot;]/li[@class=&quot;Suggestion LocationSearch Suggestion__categoryName&quot;]</value>
      <webElementGuid>4793099c-693b-4e57-be4f-cf21d0a6bbba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autocompleteSearch']/div/div/ul/li</value>
      <webElementGuid>2ef731f7-31b3-4f9c-b6c5-48069c2c5b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airport transfer'])[2]/following::li[1]</value>
      <webElementGuid>3329e272-4d59-4d94-8edb-d4a8d38af252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activities'])[2]/following::li[2]</value>
      <webElementGuid>8269f48f-b7f9-40c9-b4dc-363b39c0e9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li</value>
      <webElementGuid>3495d2e0-01b9-4b6c-8ac8-f1a6ca5cc535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'TokyoJapanCity' or . = 'TokyoJapanCity')]</value>
      <webElementGuid>0bde2643-fc95-4022-8899-d283d28b87ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
