<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Learn more</name>
   <tag></tag>
   <elementGuidId>2f47c9e1-183e-4b76-9e11-90470c4d1021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/div/a/button/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>617d9434-d368-47a7-b239-176ccc009c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Spanstyled__SpanStyled-sc-16tp9kb-0 jYmZbG kite-js-Span </value>
      <webElementGuid>78b6307d-f99d-4c9b-b9b2-2ad2a33d6f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>sherpa-banner-btn</value>
      <webElementGuid>a516b4be-ae27-48c6-befe-edfd2491679d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn more</value>
      <webElementGuid>a02dc99e-0521-42db-8012-784b6b858b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 cNTHVT&quot;]/a[@class=&quot;Box-sc-kv6pi1-0 iyqcnt&quot;]/button[@class=&quot;Buttonstyled__ButtonStyled-sc-5gjk6l-0 hfbtLY&quot;]/div[@class=&quot;BaseButtonstyled__HiddenToggler-sc-12j2fzo-2 fMuMFt&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu&quot;]/span[@class=&quot;Spanstyled__SpanStyled-sc-16tp9kb-0 jYmZbG kite-js-Span&quot;]</value>
      <webElementGuid>e27cd61e-d8b2-471e-a62b-4045196710a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/div/a/button/div/div/span</value>
      <webElementGuid>ad2be522-70b7-436a-adf1-15489b1a1023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveling internationally? Get updated information on COVID-19 travel guidance and restrictions.'])[1]/following::span[1]</value>
      <webElementGuid>39adb3d0-9b2d-4a17-b160-73aa20a4c21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List your place'])[1]/following::span[3]</value>
      <webElementGuid>228b405d-3889-4707-b6d4-b0948beec8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels &amp; Homes'])[2]/preceding::span[1]</value>
      <webElementGuid>91375713-71aa-4f9d-b9e6-354e81155b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private stays'])[1]/preceding::span[1]</value>
      <webElementGuid>c8702f23-56ae-4e8a-9e27-e2db125325e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Learn more']/parent::*</value>
      <webElementGuid>9a0a3d8e-561d-4d95-8a0f-c66a0b2969ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/div/div/span</value>
      <webElementGuid>529e58c5-b96e-45f9-bae4-68fea841e1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Learn more' or . = 'Learn more')]</value>
      <webElementGuid>dfb11216-8c4f-4fa9-aee0-2a7cf70cde9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
