<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Traveling internationally Get updated _e9f6b2</name>
   <tag></tag>
   <elementGuidId>68cfd920-a878-4287-af54-c6d9128f66d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Spanstyled__SpanStyled-sc-16tp9kb-0.gwICfd.kite-js-Span.Box-sc-kv6pi1-0.cFizrt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cff9d31a-d45c-4cae-a12e-93cd7081446d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Spanstyled__SpanStyled-sc-16tp9kb-0 gwICfd kite-js-Span Box-sc-kv6pi1-0 cFizrt</value>
      <webElementGuid>5d5195fa-6de1-4580-a453-07375208fff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>banner-description</value>
      <webElementGuid>43605415-bd7e-4bdd-9643-ed91891b045b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Traveling internationally? Get updated information on COVID-19 travel guidance and restrictions.</value>
      <webElementGuid>64507195-01f8-4bbf-82a2-2758fae40cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 cNTHVT&quot;]/span[@class=&quot;Spanstyled__SpanStyled-sc-16tp9kb-0 gwICfd kite-js-Span Box-sc-kv6pi1-0 cFizrt&quot;]</value>
      <webElementGuid>f11b7abc-36e8-4ba9-a10a-1b7b406fe418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/div/span</value>
      <webElementGuid>5bb19631-cc8d-4071-b4c0-078fa9bb1564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List your place'])[1]/following::span[2]</value>
      <webElementGuid>f00d1edb-54c4-40a2-aa71-d7878af7c864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::span[3]</value>
      <webElementGuid>10cb2bfa-3634-4cf5-9a32-6013df1337d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::span[1]</value>
      <webElementGuid>fde525e9-361e-4cd1-9de2-7282def57d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels &amp; Homes'])[2]/preceding::span[2]</value>
      <webElementGuid>51c16990-658f-49f4-956a-2c521c598a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Traveling internationally? Get updated information on COVID-19 travel guidance and restrictions.']/parent::*</value>
      <webElementGuid>8b93d09d-b842-4c75-8b27-5731ab55809c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/span</value>
      <webElementGuid>973c6775-8db8-4fb5-b2b7-7f3e78841757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Traveling internationally? Get updated information on COVID-19 travel guidance and restrictions.' or . = 'Traveling internationally? Get updated information on COVID-19 travel guidance and restrictions.')]</value>
      <webElementGuid>1f8aeedf-4758-4faf-992e-744b7e34c64e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
