<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SEARCH</name>
   <tag></tag>
   <elementGuidId>6ec6cb3b-c3ea-421f-b9f4-edf5b8448959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SearchBoxContainer']/div[2]/div/button/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0505b6a-7619-478c-9a73-cf8a00b7276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Spanstyled__SpanStyled-sc-16tp9kb-0 bXsPY kite-js-Span </value>
      <webElementGuid>c512128e-e13a-41b8-8019-d0fcb5d27f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>8bf8563f-ea4a-4edf-8ed8-24464f48001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBoxContainer&quot;)/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu TabContent__Search--button&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  hwyJDv&quot;]/button[@class=&quot;Buttonstyled__ButtonStyled-sc-5gjk6l-0 iCZpGI Box-sc-kv6pi1-0 fDMIuA&quot;]/div[@class=&quot;BaseButtonstyled__HiddenToggler-sc-12j2fzo-2 fMuMFt&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 hRUYUu&quot;]/span[@class=&quot;Spanstyled__SpanStyled-sc-16tp9kb-0 bXsPY kite-js-Span&quot;]</value>
      <webElementGuid>b04c6b54-7600-44a5-9a28-22e88b711f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBoxContainer']/div[2]/div/button/div/div/span</value>
      <webElementGuid>43ef1735-f813-4602-958a-2a7aae753479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::span[2]</value>
      <webElementGuid>3c9f7542-1b5d-4967-a38e-cff35f2eaf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight'])[1]/following::span[3]</value>
      <webElementGuid>73877d50-0f5e-4d50-8826-b5787d20b455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top destinations in India'])[1]/preceding::span[1]</value>
      <webElementGuid>dc56302e-0f3f-4328-97c9-81acb15ef63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Delhi and NCR'])[1]/preceding::span[2]</value>
      <webElementGuid>b85c4098-3e29-448b-bdc7-066a899c80c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>f8f2bfba-3f4b-4768-9269-aa75164bc00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/div/div/span</value>
      <webElementGuid>991ce04b-4d16-47cd-a401-ced1a839e53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>81df9b54-ca03-4c11-8eee-30ba2faaa2b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
