<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bangalore</name>
   <tag></tag>
   <elementGuidId>72f571b6-0749-4e32-a163-fddb117e9312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-react-root']/div/div/div/div/div/div/section[4]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ade951a-43e1-4769-9528-cbd55e1f83d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TopDestinationItem__City</value>
      <webElementGuid>6ccca8a2-1519-439e-9cd2-9e7aff19fd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bangalore</value>
      <webElementGuid>7140b0af-f93f-44b7-b5a3-123899d30bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-react-root&quot;)/div[@class=&quot;HomeReactContainer&quot;]/div[@class=&quot;HomeBody&quot;]/div[@class=&quot;TopDestinationRailStandard&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  juRSWL&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  juRSWL&quot;]/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  jBZTAM sc-fKFyDc jAyZjG&quot;]/section[@class=&quot;sc-bdfBwQ sc-gsTCUz eFiHvZ sc-bBXqnf bGwFiF scroll-snap-none&quot;]/div[@class=&quot;TopDestinationItem&quot;]/a[@class=&quot;Linkstyled__LinkStyled-sc-17yyd6k-0 hbfbVb Box-sc-kv6pi1-0 gdVBgs&quot;]/span[@class=&quot;TopDestinationItem__City&quot;]</value>
      <webElementGuid>1d5feb1c-d938-4b87-a149-1c80307beef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-react-root']/div/div/div/div/div/div/section[4]/div/a/span</value>
      <webElementGuid>a629c4a9-0722-4c8b-a0d5-c0863f9952f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai'])[1]/following::span[2]</value>
      <webElementGuid>36c0ae62-8c0d-42ce-8597-b2e318b7ea5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goa'])[1]/following::span[4]</value>
      <webElementGuid>38179dbd-858c-47ee-a58f-05fa981faefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[1]/preceding::span[2]</value>
      <webElementGuid>aa40ea3e-8506-497d-ae49-ed347dbbfde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hyderabad'])[1]/preceding::span[4]</value>
      <webElementGuid>5cb3e99b-abd5-4b27-9655-54ca0d7163b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bangalore']/parent::*</value>
      <webElementGuid>5aa2c0aa-a30e-483a-8de6-77643346746e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/a/span</value>
      <webElementGuid>1d718a3c-9141-40f6-ad2b-cdd7fc7d0854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bangalore' or . = 'Bangalore')]</value>
      <webElementGuid>6bc6ca2f-09e7-42c0-9320-5f96f82ed53c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
