<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(21208)_common-checkboxIndicator</name>
   <tag></tag>
   <elementGuidId>282f8134-aee4-4942-97e1-b624178f435d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.price-list > li > label.common-customCheckbox.vertical-filters-label > div.common-checkboxIndicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[3]/ul/li/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcc03af4-830d-4c19-a85d-5c87c7d6a443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>common-checkboxIndicator</value>
      <webElementGuid>3c44c49d-1ef1-432e-a64a-b70f75faa387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[1]/main[@class=&quot;search-base&quot;]/div[@class=&quot;row-base&quot;]/div[@class=&quot;search-leftContainer column-base&quot;]/section[1]/div[@class=&quot;condition-render-verticalFilters condition-render-boundary-top&quot;]/div[@class=&quot;vertical-filters-filters&quot;]/ul[@class=&quot;price-list&quot;]/li[1]/label[@class=&quot;common-customCheckbox vertical-filters-label&quot;]/div[@class=&quot;common-checkboxIndicator&quot;]</value>
      <webElementGuid>bf1949b9-f5df-49b1-8e6e-584cd94d79f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/main/div[3]/div/section/div/div[3]/ul/li/label/div</value>
      <webElementGuid>d79c9535-8e38-4aca-bc87-a0b70e9ec6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/label/div</value>
      <webElementGuid>4b99ec42-cf87-4dfa-ad6e-3c99cd5e3a53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
