<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_wishlist</name>
   <tag></tag>
   <elementGuidId>398eaf13-18a8-406b-b384-c162ea5eb585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='desktopSearchResults']/div[2]/section/ul/li/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b7e1f2f-98b1-4170-8282-dc0b30c66412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-wishlistFlex product-actionsButton product-wishlist </value>
      <webElementGuid>6a393f85-1ff3-4055-8755-492799899ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>wishlist</value>
      <webElementGuid>94220209-5666-4805-96bb-f13b262db29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktopSearchResults&quot;)/div[@class=&quot;search-searchProductsContainer row-base&quot;]/section[1]/ul[@class=&quot;results-base&quot;]/li[@class=&quot;product-base&quot;]/div[@class=&quot;product-actions&quot;]/span[@class=&quot;product-wishlistFlex product-actionsButton product-wishlist&quot;]</value>
      <webElementGuid>4f8cd326-d3af-4686-ad09-b052b3b9881a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopSearchResults']/div[2]/section/ul/li/div[4]/span</value>
      <webElementGuid>3a0e5c44-565b-471b-9608-8f0074cba3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW SIMILAR'])[1]/following::span[1]</value>
      <webElementGuid>524847df-38e9-479e-962f-fd2b4a9459d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(70% OFF)'])[1]/following::span[3]</value>
      <webElementGuid>96a7ac1b-d984-4455-8b6e-d0b75a623a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a size'])[1]/preceding::span[2]</value>
      <webElementGuid>d1534824-486f-40ba-a7d1-fc7ff577b1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UK7'])[2]/preceding::span[4]</value>
      <webElementGuid>66b21271-6e36-454f-abf5-41fc545c0099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='wishlist']/parent::*</value>
      <webElementGuid>11f5d4f6-b37f-4b45-af5e-4461c238d376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[4]/span</value>
      <webElementGuid>bb542951-2d7e-4469-a4ac-0bc14c37849e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'wishlist' or . = 'wishlist')]</value>
      <webElementGuid>e1d89e0a-89da-4ede-bf65-c0dcc69f43b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
