<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Show More_personalize-editPhotoTip spri_de540c</name>
   <tag></tag>
   <elementGuidId>86928875-27a3-4b05-adc1-da4d86211650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.personalize-editPhotoTip.sprites-photoEditTip.giftcard-sprite.personalize-show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/div/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19731516-c38a-45af-8b09-2f581507b0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>personalize-editPhotoTip sprites-photoEditTip giftcard-sprite
                    personalize-show</value>
      <webElementGuid>7c5e0978-51ae-4427-bd00-0f60ce332839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[@class=&quot;index-base&quot;]/div[@class=&quot;personalize-page&quot;]/div[@class=&quot;personalize-occasionBg&quot;]/div[@class=&quot;personalize-occasionCard&quot;]/div[@class=&quot;personalize-occasionCardImageContainer&quot;]/div[@class=&quot;personalize-occasionCardImageDiv&quot;]/div[@class=&quot;personalize-editPhotoTip sprites-photoEditTip giftcard-sprite
                    personalize-show&quot;]</value>
      <webElementGuid>dde74ee7-8056-44df-a6ca-665ccf9686af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>a15d02de-bb0b-4933-a5a3-fdcdf0390976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>5aa3a974-ee1b-4bd9-8b1b-f906c9560255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
