<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Watches  Wearables</name>
   <tag></tag>
   <elementGuidId>6d4303f6-55d1-4016-9c5c-fc2ce616108c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[2]/div/div/div/div/li/ul/li[13]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6eac2b1-d22c-4eaf-b77c-68beba01b1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/women-watches</value>
      <webElementGuid>323c982c-88b2-4acf-bb5b-38630a9a9ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-categoryName</value>
      <webElementGuid>179e6a7f-04e6-43d5-b589-75e65175ab62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>213</value>
      <webElementGuid>bfb62d60-0c85-455d-9db3-edefc41c528c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watches &amp; Wearables</value>
      <webElementGuid>a339eb5b-4d0f-4213-9c29-10a2059a095f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/nav[@class=&quot;desktop-navbar&quot;]/div[@class=&quot;desktop-navLinks&quot;]/div[@class=&quot;desktop-navContent&quot;]/div[@class=&quot;desktop-navLink&quot;]/div[@class=&quot;desktop-backdropStyle&quot;]/div[@class=&quot;desktop-paneContent&quot;]/div[@class=&quot;desktop-categoryContainer&quot;]/li[@class=&quot;desktop-oddColumnContent&quot;]/ul[@class=&quot;desktop-navBlock&quot;]/li[13]/a[@class=&quot;desktop-categoryName&quot;]</value>
      <webElementGuid>f7ad0ed7-d804-4953-a115-9ace2c92f035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/nav/div/div[2]/div/div/div/div/li/ul/li[13]/a</value>
      <webElementGuid>7f88665e-4dbf-4faa-b44c-2f209ac3eb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Watches &amp; Wearables')]</value>
      <webElementGuid>3f208ed4-5374-4d44-876f-4b39f900e787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belts, Scarves &amp; More'])[1]/following::a[1]</value>
      <webElementGuid>179e2e76-c55b-477f-8c94-b573cf6c8811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jackets'])[2]/following::a[2]</value>
      <webElementGuid>930e1ff0-c937-4b63-8312-71c3a7241e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Western Wear'])[1]/preceding::a[1]</value>
      <webElementGuid>32bd3c5d-e886-41a4-85d5-91e3d4367d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dresses'])[1]/preceding::a[2]</value>
      <webElementGuid>660fcad9-42ec-46f5-8e77-c7b54e1bd553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watches &amp; Wearables']/parent::*</value>
      <webElementGuid>1831e3ac-439a-4805-8964-42271ca64ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/women-watches')]</value>
      <webElementGuid>8b603f50-3725-41d6-9711-c58b8914b911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/li/ul/li[13]/a</value>
      <webElementGuid>870ece26-8553-4ed6-bec4-949294ee8460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/women-watches' and (text() = 'Watches &amp; Wearables' or . = 'Watches &amp; Wearables')]</value>
      <webElementGuid>1f0a24eb-3ecc-404a-b066-28a3c6b24f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
