<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wedding</name>
   <tag></tag>
   <elementGuidId>d8fe9013-bc11-4e97-8cf0-ca5ce0b5a639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.occasionspicker-occasionDiv > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mountRoot']/div/div/div[2]/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b6df668-84a1-4ed5-a6da-fe104c616db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wedding</value>
      <webElementGuid>38f1ddd5-56d5-4b76-9fbe-a0d529676b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountRoot&quot;)/div[@class=&quot;index-base&quot;]/div[@class=&quot;personalize-page&quot;]/div[@class=&quot;personalize-occasionBg&quot;]/div[@class=&quot;personalize-occasionsListContainer&quot;]/div[1]/div[1]/div[@class=&quot;occasionspicker-occasionsContainer&quot;]/div[@class=&quot;occasionspicker-occasionDiv&quot;]/div[1]</value>
      <webElementGuid>29d9dffa-afbe-4010-964e-d7c511193d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountRoot']/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>8489c98d-913f-4d4c-b132-f28bc5d5d5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESIGN GIFT CARD'])[1]/following::div[7]</value>
      <webElementGuid>258b334b-ff06-47ce-bcda-5a1a1fb12e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::div[12]</value>
      <webElementGuid>6b21bcc5-7e9c-4b28-9571-c00adbdba8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BFF'])[1]/preceding::div[1]</value>
      <webElementGuid>aa6e7038-b8ba-4360-945d-c9be07760197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Durga Puja'])[1]/preceding::div[3]</value>
      <webElementGuid>69bd1304-230e-43fc-894c-def63cf00359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wedding']/parent::*</value>
      <webElementGuid>9fce5f0c-d705-4d32-b6be-9fc8dd29dcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>f58da1a0-6616-438a-89f0-91ee4641a0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Wedding' or . = 'Wedding')]</value>
      <webElementGuid>5add184f-e91a-4546-9020-84a21cb23df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
