<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms of Use</name>
   <tag></tag>
   <elementGuidId>b14f5d48-c029-4362-b39a-39557e5386f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.midLinks > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reactPageContent']/div/div/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70682236-e529-4daf-9b3a-b7384f91250b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/termsofuse</value>
      <webElementGuid>9a01c650-ec69-48a6-9734-4f3cb903d2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms of Use</value>
      <webElementGuid>3ccdbca7-3797-472b-95bf-8ba6ca6e430a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactPageContent&quot;)/div[@class=&quot;authPage&quot;]/div[1]/div[@class=&quot;signInContainer&quot;]/div[@class=&quot;mobileInputContainer&quot;]/div[@class=&quot;midLinks&quot;]/a[1]</value>
      <webElementGuid>c0ae47df-07b5-43be-82c7-7067e935bea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactPageContent']/div/div/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>7347fcd2-09b1-441f-8eb7-539cd72c71bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms of Use')]</value>
      <webElementGuid>96ee24f4-63ff-4789-a23e-45be6d369a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[1]</value>
      <webElementGuid>daea2e4c-5877-47e4-a42d-bdab7e5eb6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE'])[1]/preceding::a[2]</value>
      <webElementGuid>1bc23bad-f268-4136-b716-bb67165e0499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terms of Use']/parent::*</value>
      <webElementGuid>49e8de12-9aa4-48c4-b9e7-c6f902a9034e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/termsofuse')]</value>
      <webElementGuid>aa4be14f-2f4f-45dd-98a6-4df824a0524c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>7aa9fc1b-18fb-486f-a6f4-e23fa97c969f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/termsofuse' and (text() = 'Terms of Use' or . = 'Terms of Use')]</value>
      <webElementGuid>8a634812-b492-4332-b13a-824c9e76f872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
