<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_STUDIO</name>
   <tag></tag>
   <elementGuidId>712b5b5a-ca11-48ee-a29a-7b26606638f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='redirectPageTo(&quot;/studio/home&quot;)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ffbd84a3-c891-45f5-90c8-b44005c13cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-navcontent</value>
      <webElementGuid>f4aeafb3-f2d9-4a71-a18b-d8f5d2d763e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectPageTo(&quot;/studio/home&quot;)</value>
      <webElementGuid>81d36c47-5303-466b-9fc0-9b6247c2c5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STUDIO</value>
      <webElementGuid>899f9795-f733-42f3-864e-fcd5e040fffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mountPoint&quot;)/div[1]/div[@class=&quot;layout&quot;]/div[@class=&quot;desktop-header-container&quot;]/div[@class=&quot;desktop-navlink-container&quot;]/div[@class=&quot;desktop-navcontent&quot;]</value>
      <webElementGuid>8cecc17e-6fee-4da4-b41e-a0dba92b92b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='redirectPageTo(&quot;/studio/home&quot;)']</value>
      <webElementGuid>6fbc6784-4870-4aef-968a-7b8cd5a1b568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mountPoint']/div/div[2]/div/div[2]/div[5]</value>
      <webElementGuid>cbff1b9f-d8ee-471c-b374-cca3e751dd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME LIVING'])[1]/following::div[1]</value>
      <webElementGuid>110198f1-9123-49d3-a314-257f7ab3169b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIDS'])[1]/following::div[2]</value>
      <webElementGuid>cdff2f98-b2ba-4c58-88b2-94bbc39013c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/preceding::div[1]</value>
      <webElementGuid>0666169e-2c00-495a-9693-d452c6401def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bag'])[1]/preceding::div[1]</value>
      <webElementGuid>4fcd2de9-1bc9-46e4-8b9d-79d9660103b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='STUDIO']/parent::*</value>
      <webElementGuid>14d4e60e-0902-4376-bfec-f9138060708b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
      <webElementGuid>1bbd63c9-27b0-4fec-a2ae-14aef5fedde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'STUDIO' or . = 'STUDIO')]</value>
      <webElementGuid>7c043b9f-a9da-4f67-a325-0a6e776870f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
