<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sent to9014592352_otp3</name>
   <tag></tag>
   <elementGuidId>0df09081-2c5e-4023-b05e-295742ca6b2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp3&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c48b1de7-4062-4d33-84a5-12d7ad78e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp3</value>
      <webElementGuid>17447b1c-8624-448c-8f12-90697992d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>94424599-017b-4ffc-8c42-69e6cef76cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9571efc4-36f3-4e36-9808-266fefd03d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7a5a18d9-4674-4a2e-b704-cb501dae3e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e04693c0-3243-442e-a089-e739a4525ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>fca48506-53b6-4d39-be11-3004452794e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactPageContent&quot;)/div[@class=&quot;verificationContainer&quot;]/div[@class=&quot;mobContainer&quot;]/div[@class=&quot;otpContainer&quot;]/input[4]</value>
      <webElementGuid>d18826c0-9395-4e8f-9805-7f5371aa82b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp3']</value>
      <webElementGuid>c88ebc71-92bb-42ce-8745-50599f14bbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactPageContent']/div/div[2]/div/input[4]</value>
      <webElementGuid>d5fd7e19-bd38-4df0-8392-936034ae7cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>e314f408-dda2-4093-99cc-6b18cd465574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otp3' and @type = 'tel']</value>
      <webElementGuid>e913be62-b2c4-4309-927a-484a1cff3987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
