<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sent to9014592352_otp1</name>
   <tag></tag>
   <elementGuidId>ba2d3a3f-a1ee-47fb-8d01-c9a783c39a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15535cf1-303a-4c03-95e4-ac12511f7f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp1</value>
      <webElementGuid>8538f0b9-a2f3-4ef5-b876-8e3a23e830b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>18969abd-9879-476a-abe9-144a3346856a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9454508-53d8-4c79-95c0-ed2fcb906810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d8a0885f-0c88-4b90-8914-adf9443be523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4a77d5d-8f7c-479a-8b88-a7cbd07e8b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>db096849-f3a9-4f0f-aa1f-f6fc15680e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactPageContent&quot;)/div[@class=&quot;verificationContainer&quot;]/div[@class=&quot;mobContainer&quot;]/div[@class=&quot;otpContainer&quot;]/input[2]</value>
      <webElementGuid>0faa4f78-8788-441a-977e-cfdd6049297a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp1']</value>
      <webElementGuid>9db2de1a-ab1d-45c7-aa53-e139b843c904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactPageContent']/div/div[2]/div/input[2]</value>
      <webElementGuid>ebf1b8d8-0783-41bb-aea8-7bcd542a7ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>dc8977d5-b42f-46b2-af11-2c8e43f513e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otp1' and @type = 'tel']</value>
      <webElementGuid>f5cfe2e5-ba66-413a-a319-c0fb3b758ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
