<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sent to9014592352_otp2</name>
   <tag></tag>
   <elementGuidId>cd5f5220-2057-45fc-ab9e-101244c412ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac519d30-92c4-4967-a3c1-ba0367b4ed0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp2</value>
      <webElementGuid>d1bb0db6-8c96-46f0-9c0e-67dc12dc5af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9c4a37cf-5d50-44f6-9982-9c91edf786c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>26b57f75-29ca-4d37-a105-5f142fefd6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>45def0a0-f075-462e-beb1-e9415c35119b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dfaae35-0a7c-4bb7-9856-1506a4b646d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b0acc59b-625f-4ef1-8d2d-653dc908fd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactPageContent&quot;)/div[@class=&quot;verificationContainer&quot;]/div[@class=&quot;mobContainer&quot;]/div[@class=&quot;otpContainer&quot;]/input[3]</value>
      <webElementGuid>13a112e5-7adc-46e5-9b55-bbd672c16aba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp2']</value>
      <webElementGuid>d5bfa6e5-2ecb-4642-9188-79435fc1c40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactPageContent']/div/div[2]/div/input[3]</value>
      <webElementGuid>7d773591-a27e-4ccd-bce1-393681f1299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>9889e002-8b37-44d3-ae2c-f66b576019b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otp2' and @type = 'tel']</value>
      <webElementGuid>b46d6b92-f561-4fc9-9e27-0b2bcf6bf344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
