<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sent to9014592352_otp0</name>
   <tag></tag>
   <elementGuidId>1d8a8352-5ce5-45c3-9285-b5d5f237f3dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c1b3bce-d6fc-4776-b408-d1a9b046e0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp0</value>
      <webElementGuid>21aedea8-66fe-45dc-a5a6-49d0f696f156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d593b962-480b-47c7-b58a-0ba331b0fe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>367f9a00-7371-43f3-aad7-7586faf95a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c2c48a6-357d-41f3-8ea1-826253416253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>221b9bd9-ac24-4d38-9097-7726c46eee44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6aa923b4-d67a-4485-af64-f1b8b1fc3bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reactPageContent&quot;)/div[@class=&quot;verificationContainer&quot;]/div[@class=&quot;mobContainer&quot;]/div[@class=&quot;otpContainer&quot;]/input[1]</value>
      <webElementGuid>bf32a0c7-4a13-4996-ae08-05ec5fcdbef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp0']</value>
      <webElementGuid>b0e47a10-5e10-4588-ba85-3eeb1e3e8907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reactPageContent']/div/div[2]/div/input</value>
      <webElementGuid>978e0c5d-d106-45d1-8f80-15b3119c8cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>cd5d3d85-0d62-4902-b82d-4c1f40d9499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'otp0' and @type = 'tel']</value>
      <webElementGuid>37f3365d-9005-44f7-971c-4ec15bd2d079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
