<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Day Use Stays</name>
   <tag></tag>
   <elementGuidId>04a5c792-72f1-46a7-9a74-4d54ee6e96fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-bdfBwQ.sc-gsTCUz.hWygYf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d53773c-3274-4650-aa6b-01d761d2a657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3403524f-3ffc-4d13-8277-4c5333c8e32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c8ff19af-160c-4725-88b3-6803404ed571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Day Use Stays</value>
      <webElementGuid>cde9e0a1-c2e4-49c8-b861-3291ad33cbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>funnel-switcher</value>
      <webElementGuid>c6997934-bf90-4a8d-8285-2075e87e1a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hh-booking-duration-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>85397d59-bc65-40da-b02e-618dbd266cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bdfBwQ sc-gsTCUz  hWygYf</value>
      <webElementGuid>99f5335d-ec74-4775-97c3-1d27c9bb6f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Day Use Stays</value>
      <webElementGuid>02427801-9ad1-4132-850c-c0d51a9f04fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;funnel-toggles-container&quot;)/div[@class=&quot;sc-bdfBwQ sc-gsTCUz  juRSWL&quot;]/button[@class=&quot;sc-bdfBwQ sc-gsTCUz  hWygYf&quot;]</value>
      <webElementGuid>bf409182-3fa3-4582-ab5a-fc4626b6e029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>8479681d-97f9-46a0-9812-2522715e04fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='funnel-toggles-container']/div[2]/button</value>
      <webElementGuid>0a965122-425c-4253-8542-c038ebc6d33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overnight Stays'])[1]/following::button[1]</value>
      <webElementGuid>1a4c0df8-6fd1-42bb-ba7c-17d251f945e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airport transfer'])[2]/following::button[2]</value>
      <webElementGuid>a725e0b6-319a-45ef-afc3-3de97075dbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday'])[1]/preceding::button[1]</value>
      <webElementGuid>aab1986d-929b-4345-88ae-45798e7b3fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>a1e3ca16-9db1-4163-aab5-2c3f9af6f063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Day Use Stays' or . = 'Day Use Stays')]</value>
      <webElementGuid>d0597b62-2ef9-45d3-b8c0-942ca2c1a4f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
