<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_English</name>
   <tag></tag>
   <elementGuidId>de524de3-0ce8-4649-9905-40e4aade0e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Box-sc-kv6pi1-0.fYsaGj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d8d11407-2339-421e-a704-421f3678eae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbae82a1-ab7d-4344-a5b0-fef5881c4a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>845986e2-791e-499a-93c5-4cf3eac1f25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>language-container-selected-language</value>
      <webElementGuid>c99123b5-3424-46ba-a77d-6eb579cfcbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selenium</name>
      <type>Main</type>
      <value>language-container-selected-language</value>
      <webElementGuid>57dd8525-5332-4723-94bc-b87c3d246035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>en-us</value>
      <webElementGuid>814692ee-3de7-4d5c-9b85-5dcff2da199c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Box-sc-kv6pi1-0 fYsaGj</value>
      <webElementGuid>7247dcfa-d7ff-4635-b0ec-fa1539a593ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>9ab01ae4-ec69-4c7a-a369-f88d6e3202b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome no-js&quot;]/body[@class=&quot;desktop  ltr themed theme-agoda&quot;]/div[13]/div[@class=&quot;Popoverstyled__PopoverWrapperStyled-sc-19qsf81-1 hDKwkn&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 bJwhFV&quot;]/div[@class=&quot;UserMenuLinksstyled__MenuGroup-sc-179518m-5 jZRiFr&quot;]/ul[@class=&quot;Liststyled__ListStyled-sc-ksl08h-0 yYPQk SettingLinks&quot;]/li[1]/div[@class=&quot;UserMenuLinksstyled__MenuItem-sc-179518m-1 elAtiU&quot;]/div[@class=&quot;Box-sc-kv6pi1-0 fYsaGj&quot;]</value>
      <webElementGuid>5c61e660-db2f-47a8-bbba-2e2dcdf29686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[3]</value>
      <webElementGuid>2ea91a42-b777-4974-8337-a352cfdf4c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create account'])[2]/following::div[5]</value>
      <webElementGuid>0d13c094-3ef0-44b8-981c-bac309b20114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indian Rupee'])[1]/preceding::div[3]</value>
      <webElementGuid>9b00e9f9-126c-4654-a53a-f63f36347db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>c4b90869-e987-4b62-b9da-876051301645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>a0472c13-eb1a-4707-a5e6-f2ebb57d21bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
